name: C++ CI Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup gRPC
      uses: eWaterCycle/setup-grpc@v5
      with:
        grpc-version: '1.51.1' # Укажите версию gRPC, которая вам нужна

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake protobuf-compiler

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu/cmake/grpc;/usr/lib/x86_64-linux-gnu/cmake/protobuf" ..

    - name: Debug gRPC setup
      run: |
        echo "PATH: $PATH"
        echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
        echo "GRPC_ROOT: $GRPC_ROOT"
        which protoc-gen-grpc
        protoc --version


    - name: Build project
      run: |
        cd build && cmake --build . -- -j$(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: updater_service_build
        path: build/updater_service
