name: C++ CI Build

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libprotobuf-dev protobuf-compiler

    - name: Install gRPC and Protobuf from source
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf libtool pkg-config cmake git
        git clone --recurse-submodules -b v1.56.0 https://github.com/grpc/grpc
        cd grpc
        mkdir -p cmake/build
        cd cmake/build
        cmake ../..
        make -j$(nproc)
        sudo make install
        sudo ldconfig


    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        cmake --build . -- -j$(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: updater_service_build
        path: build/updater_service
